-- Create Database
USE [master];

CREATE DATABASE [c3o_logger_acme] ON  PRIMARY 
(	NAME = N'c3o_logger_acme', FILENAME = N'C:\web\c3o\elmah.net\sql\c3o_logger_acme.mdf', SIZE = 2048KB, MAXSIZE = 10MB, FILEGROWTH = 1024KB )
 LOG ON ( NAME = N'c3o_logger_acme_log', FILENAME = N'C:\web\c3o\elmah.net\sql\c3o_logger_acme_log.ldf', SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%);
ALTER DATABASE [c3o_logger_acme] SET COMPATIBILITY_LEVEL = 100;
ALTER DATABASE [c3o_logger_acme] SET ANSI_NULL_DEFAULT OFF ;
ALTER DATABASE [c3o_logger_acme] SET ANSI_NULLS OFF ;
ALTER DATABASE [c3o_logger_acme] SET ANSI_PADDING OFF 
ALTER DATABASE [c3o_logger_acme] SET ANSI_WARNINGS OFF ;
ALTER DATABASE [c3o_logger_acme] SET ARITHABORT OFF ;
ALTER DATABASE [c3o_logger_acme] SET AUTO_CLOSE OFF ;
ALTER DATABASE [c3o_logger_acme] SET AUTO_CREATE_STATISTICS ON ;
ALTER DATABASE [c3o_logger_acme] SET AUTO_SHRINK OFF ;
ALTER DATABASE [c3o_logger_acme] SET AUTO_UPDATE_STATISTICS ON ;
ALTER DATABASE [c3o_logger_acme] SET CURSOR_CLOSE_ON_COMMIT OFF ;
ALTER DATABASE [c3o_logger_acme] SET CURSOR_DEFAULT  GLOBAL ;
ALTER DATABASE [c3o_logger_acme] SET CONCAT_NULL_YIELDS_NULL OFF ;
ALTER DATABASE [c3o_logger_acme] SET NUMERIC_ROUNDABORT OFF ;
ALTER DATABASE [c3o_logger_acme] SET QUOTED_IDENTIFIER OFF ;
ALTER DATABASE [c3o_logger_acme] SET RECURSIVE_TRIGGERS OFF ;
ALTER DATABASE [c3o_logger_acme] SET DISABLE_BROKER ;
ALTER DATABASE [c3o_logger_acme] SET AUTO_UPDATE_STATISTICS_ASYNC OFF ;
ALTER DATABASE [c3o_logger_acme] SET DATE_CORRELATION_OPTIMIZATION OFF ;
ALTER DATABASE [c3o_logger_acme] SET TRUSTWORTHY OFF ;
ALTER DATABASE [c3o_logger_acme] SET ALLOW_SNAPSHOT_ISOLATION OFF ;
ALTER DATABASE [c3o_logger_acme] SET PARAMETERIZATION SIMPLE ;
ALTER DATABASE [c3o_logger_acme] SET READ_COMMITTED_SNAPSHOT OFF ;
ALTER DATABASE [c3o_logger_acme] SET HONOR_BROKER_PRIORITY OFF ;
ALTER DATABASE [c3o_logger_acme] SET  READ_WRITE ;
ALTER DATABASE [c3o_logger_acme] SET RECOVERY SIMPLE ;
ALTER DATABASE [c3o_logger_acme] SET  MULTI_USER ;
ALTER DATABASE [c3o_logger_acme] SET PAGE_VERIFY CHECKSUM  ;
ALTER DATABASE [c3o_logger_acme] SET DB_CHAINING OFF ;