-- Create tagging
CREATE TABLE dbo.Tags
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name nvarchar(1000) NULL,
	Icon varchar(20) NULL,
	Color varchar(10) NULL
	)  ON [PRIMARY];


ALTER TABLE dbo.Tags ADD CONSTRAINT 	DF_Tags_Icon DEFAULT ('tag') FOR Icon;
ALTER TABLE dbo.Tags ADD CONSTRAINT	PK_Tags PRIMARY KEY CLUSTERED 	(	Id	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];


CREATE TABLE dbo.MessageTags
(
	MessageId bigint NOT NULL,
	PersonId bigint NOT NULL,
	TagId int NOT NULL,
	TaggedById bigint NOT NULL,
)  ON [PRIMARY];

ALTER TABLE dbo.MessageTags ADD CONSTRAINT	PK_MessageTags PRIMARY KEY CLUSTERED 	(	MessageId,	PersonId,TagId	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
ALTER TABLE dbo.MessageTags ADD CONSTRAINT	FK_MessageTags_Tags FOREIGN KEY	(	TagId	) REFERENCES dbo.Tags	(	Id	) ON UPDATE  NO ACTION 	 ON DELETE  NO ACTION ;
	
